[package]
name = "feature-factory"
version = "0.1.0-a.1"
description = "A feature engineering library for Rust"
repository = "https://github.com/habedi/feature-factory"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["feature-engineering", "machine-learning", "data-science", "feature-selection", "feature-extraction"]
authors = ["Hassan Abedi <hassan.abedi.t@gmail.com>"]
homepage = "https://github.com/habedi/feature-factory"
documentation = "https://docs.rs/feature-factory"
categories = ["algorithms", "data-structures"]
edition = "2024"
rust-version = "1.85"

resolver = "2"

include = [
    "assets/**/*",
    "src/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
    "logo.png"
]

[lib]
name = "feature_factory"
path = "src/lib.rs"

[features]
default = []
binaries = []

[dependencies]
arrow = "55.2.0"
ctor = "0.5.0"
parquet = "55.2.0"
tokio = { version = "1.0", features = ["rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
thiserror = "2"
datafusion = "49.0.2"
datafusion-expr = "49.0.2"
datafusion-functions = "49.0.2"
approx = "0.5.1"
async-trait = "0.1.87"
futures = "0.3.31"
rayon = "1.10"

# Add pyo3 as an optional dependency
pyo3 = { version = "0.24.1", optional = true, features = ["macros"] }

[dev-dependencies]
criterion = { version = "0.7.0", features = ["html_reports"] }

[[bench]]
name = "project_benchmarks"
harness = false

[profile.release]
strip = "debuginfo"
panic = "abort"
codegen-units = 1
lto = true

[profile.bench]
debug = true

[profile.test]
debug = true

[profile.example]
inherits = "release"
